name: Publish

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build Intercom.Extensions.Hosting/Intercom.Extensions.Hosting.csproj --no-restore --configuration Release
    - name: Publish
      uses: laget-se/publish-nuget@v2.7.2
      with:
        INCLUDE_SYMBOLS: true
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        NUSPEC_FILE: Intercom.Extensions.Hosting.nuspec
        PROJECT_FILE_PATH: Intercom.Extensions.Hosting/Intercom.Extensions.Hosting.csproj
        VERSION_STATIC: "0.1.${{github.run_number}}-alpha"
