name: Publish

on:
  workflow_dispatch: {}

env:
  VERSION: "0.1"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - run: dotnet restore
    - run: dotnet build --configuration Release Intercom.Extensions.Hosting/Intercom.Extensions.Hosting.csproj
    - run: dotnet pack --configuration Release Intercom.Extensions.Hosting/Intercom.Extensions.Hosting.csproj --no-build -p:Version=$VERSION.${{github.run_number}}-alpha -p:PackageVersion=0.1.${{github.run_number}}-alpha -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -p:NuspecFile=Intercom.Extensions.Hosting.nuspec
    - run: dotnet nuget push Intercom.Extensions.Hosting/bin/Release/Intercom.Extensions.Hosting.$VERSION.${{github.run_number}}-alpha.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
